name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Set up project structure for GitHub Pages
        run: |
          # Ensure advanced dashboard is the default landing page
          cp Reports/advanced-dashboard.html index.html
          
          # Copy original index.html as main-dashboard.html
          cp Reports/index.html main-dashboard.html
          
          # Fix links in advanced-dashboard.html to point to main-dashboard.html
          sed -i 's/href="index.html"/href="main-dashboard.html"/g' index.html
          
          # Ensure all supporting directories and files are copied
          cp -r Reports/css .
          cp -r Reports/js .
          cp -r Reports/advanced-dashboard.html .
          
          # If there are images, copy them too
          if [ -d Reports/images ]; then
            cp -r Reports/images .
          fi
          
          # Copy any data files needed for the sample data
          if [ -d Reports/Erank_Raw_Data ]; then
            cp -r Reports/Erank_Raw_Data .
          fi
          
          echo "Successfully set up project structure for GitHub Pages"
          ls -la
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
